name: "Terraform Pipeline"

on:
  push:
    branches: [ "main" ]

jobs:
  plan_stage:
    name: "Stage 1: Plan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - uses: hashicorp/setup-terraform@v3
      - name: "Run Terraform Plan"
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_default_region: ${{ secrets.GCP_PROJECT_REGION }}
        run: |
          cd terraform
          terraform init
          terraform fmt -check
          terraform plan
          terraform plan -out=tfplan -no-color
      - name: "Archive Plan"
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

  apply_stage:
    name: "Stage 2: Apply"
    needs: plan_stage
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - uses: hashicorp/setup-terraform@v3

      - name: "Download Plan"
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-file
          path: terraform/

      - name: "Terraform Apply"
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_default_region: ${{ secrets.GCP_PROJECT_REGION }}
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
